{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"stringFromBusinessType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType","preciseIdentifier":"c:@M@StripePayments@E@STPConnectAccountBusinessType","text":"STPConnectAccountBusinessType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"businessType"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpconnectaccountparams\/stringfrombusinesstype:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/stringFromBusinessType:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stringFromBusinessType:"}],"title":"stringFromBusinessType:","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPConnectAccountParams(cm)stringFromBusinessType:","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"stringFromBusinessType:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams/stringFromBusinessType:":{"role":"symbol","title":"stringFromBusinessType:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stringFromBusinessType:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/stringFromBusinessType:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stringFromBusinessType:"}],"url":"\/documentation\/stripepayments\/stpconnectaccountparams\/stringfrombusinesstype:"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams":{"role":"symbol","title":"STPConnectAccountParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConnectAccountParams"}],"abstract":[{"type":"text","text":"Parameters for creating a Connect Account token."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountParams"}],"url":"\/documentation\/stripepayments\/stpconnectaccountparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountBusinessType":{"role":"symbol","title":"STPConnectAccountBusinessType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConnectAccountBusinessType"}],"abstract":[{"type":"text","text":"The business type of the Connect account."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountBusinessType"}],"url":"\/documentation\/stripepayments\/stpconnectaccountbusinesstype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/title","value":"STPConnectAccountParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/fragments","value":[{"kind":"identifier","text":"STPConnectAccountParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType\/title","value":"STPConnectAccountBusinessType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType\/fragments","value":[{"kind":"identifier","text":"STPConnectAccountBusinessType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}