{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus","preciseIdentifier":"c:@M@StripePayments@E@STPBankAccountStatus","text":"STPBankAccountStatus"},{"kind":"text","text":") "},{"kind":"identifier","text":"statusFromString:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"string"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpbankaccount\/statusfromstring:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/statusFromString:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"statusFromString:"}],"title":"statusFromString:","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPBankAccount(cm)statusFromString:","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"statusFromString:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount/statusFromString:":{"role":"symbol","title":"statusFromString:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"statusFromString:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/statusFromString:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"statusFromString:"}],"url":"\/documentation\/stripepayments\/stpbankaccount\/statusfromstring:"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountStatus":{"role":"symbol","title":"STPBankAccountStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankAccountStatus"}],"abstract":[{"type":"text","text":"Possible validation states for a bank account."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBankAccountStatus"}],"url":"\/documentation\/stripepayments\/stpbankaccountstatus"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount":{"role":"symbol","title":"STPBankAccount","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankAccount"}],"abstract":[{"type":"text","text":"Representation of a user’s bank account details that have been tokenized with"},{"type":"text","text":" "},{"type":"text","text":"the Stripe API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBankAccount"}],"url":"\/documentation\/stripepayments\/stpbankaccount"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus\/title","value":"STPBankAccountStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus\/fragments","value":[{"kind":"identifier","text":"STPBankAccountStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount\/title","value":"STPBankAccount"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount\/fragments","value":[{"kind":"identifier","text":"STPBankAccount"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}