{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"stringFromStatus:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus","preciseIdentifier":"c:@M@StripePayments@E@STPBankAccountStatus","text":"STPBankAccountStatus"},{"kind":"text","text":")"},{"kind":"internalParam","text":"status"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpbankaccount\/stringfromstatus:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/stringFromStatus:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stringFromStatus:"}],"title":"stringFromStatus:","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPBankAccount(cm)stringFromStatus:","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"stringFromStatus:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount/stringFromStatus:":{"role":"symbol","title":"stringFromStatus:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stringFromStatus:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/stringFromStatus:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stringFromStatus:"}],"url":"\/documentation\/stripepayments\/stpbankaccount\/stringfromstatus:"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount":{"role":"symbol","title":"STPBankAccount","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankAccount"}],"abstract":[{"type":"text","text":"Representation of a user’s bank account details that have been tokenized with"},{"type":"text","text":" "},{"type":"text","text":"the Stripe API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBankAccount"}],"url":"\/documentation\/stripepayments\/stpbankaccount"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountStatus":{"role":"symbol","title":"STPBankAccountStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankAccountStatus"}],"abstract":[{"type":"text","text":"Possible validation states for a bank account."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBankAccountStatus"}],"url":"\/documentation\/stripepayments\/stpbankaccountstatus"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount\/title","value":"STPBankAccount"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount\/fragments","value":[{"kind":"identifier","text":"STPBankAccount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus\/title","value":"STPBankAccountStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus\/fragments","value":[{"kind":"identifier","text":"STPBankAccountStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}