{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"confirmSetupIntent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams","text":"STPSetupIntentConfirmParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"setupIntentConfirmParams"},{"kind":"text","text":" "},{"kind":"identifier","text":"withAuthenticationContext:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<STPAuthenticationContext>","preciseIdentifier":"c:Qo@M@StripePayments@objc(pl)STPAuthenticationContext"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"authenticationContext"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(enum STPPaymentHandlerActionStatus, STPSetupIntent *, NSError *)","preciseIdentifier":"c:BFv(#$@M@StripePayments@E@STPPaymentHandlerActionStatus#*$@M@StripePayments@objc(cs)STPSetupIntent#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"\\param authenticationContext The authentication context used to authenticate the SetupIntent."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"\\param completion The completion block. If the status returned is "},{"type":"text","text":"STPPaymentHandlerActionStatusSucceeded"},{"type":"text","text":", the SetupIntent status will always be STPSetupIntentStatusSucceeded."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymenthandler\/confirmsetupintent:withauthenticationcontext:completion:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmSetupIntent:withAuthenticationContext:completion:","interfaceLanguage":"occ"},"abstract":[{"type":"text","text":"Confirms the SetupIntent with the provided parameters and handles any "},{"type":"text","text":"nextAction"},{"type":"text","text":" required"},{"type":"text","text":" "},{"type":"text","text":"to authenticate the SetupIntent."},{"type":"text","text":" "},{"type":"text","text":"seealso:"},{"type":"text","text":" "},{"type":"text","text":"https:\/\/stripe.com\/docs\/payments\/save-during-payment?platform=ios"},{"type":"text","text":" "},{"type":"text","text":"\\param setupIntentConfirmParams The params used to confirm the SetupIntent. Note that this method overrides the value of "},{"type":"text","text":"setupIntentConfirmParams.useStripeSDK"},{"type":"text","text":" to "},{"type":"text","text":"@YES"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"confirmSetupIntent:withAuthenticationContext:completion:"}],"title":"confirmSetupIntent:withAuthenticationContext:completion:","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPPaymentHandler(im)confirmSetupIntent:withAuthenticationContext:completion:","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"confirmSetupIntent:withAuthenticationContext:completion:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler":{"role":"symbol","title":"STPPaymentHandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandler"}],"abstract":[{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" is a utility class that confirms PaymentIntents\/SetupIntents and handles any authentication required, such as 3DS1\/3DS2 for Strong Customer Authentication."},{"type":"text","text":" "},{"type":"text","text":"It can present authentication UI on top of your app or redirect users out of your app (to e.g. their banking app)."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandler"}],"url":"\/documentation\/stripepayments\/stppaymenthandler"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/confirmSetupIntent:withAuthenticationContext:completion:":{"role":"symbol","title":"confirmSetupIntent:withAuthenticationContext:completion:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"confirmSetupIntent:withAuthenticationContext:completion:"}],"abstract":[{"type":"text","text":"Confirms the SetupIntent with the provided parameters and handles any "},{"type":"text","text":"nextAction"},{"type":"text","text":" required"},{"type":"text","text":" "},{"type":"text","text":"to authenticate the SetupIntent."},{"type":"text","text":" "},{"type":"text","text":"seealso:"},{"type":"text","text":" "},{"type":"text","text":"https:\/\/stripe.com\/docs\/payments\/save-during-payment?platform=ios"},{"type":"text","text":" "},{"type":"text","text":"\\param setupIntentConfirmParams The params used to confirm the SetupIntent. Note that this method overrides the value of "},{"type":"text","text":"setupIntentConfirmParams.useStripeSDK"},{"type":"text","text":" to "},{"type":"text","text":"@YES"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmSetupIntent:withAuthenticationContext:completion:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"confirmSetupIntent:withAuthenticationContext:completion:"}],"url":"\/documentation\/stripepayments\/stppaymenthandler\/confirmsetupintent:withauthenticationcontext:completion:"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams":{"role":"symbol","title":"STPSetupIntentConfirmParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"abstract":[{"type":"text","text":"An object representing parameters to confirm a SetupIntent object."},{"type":"text","text":" "},{"type":"text","text":"For example, you would confirm a SetupIntent when a customer hits the “Save” button on a payment method management view in your app."},{"type":"text","text":" "},{"type":"text","text":"If the selected payment method does not require any additional steps from the customer, the SetupIntent’s status will transition to "},{"type":"codeVoice","code":"STPSetupIntentStatusSucceeded"},{"type":"text","text":".  Otherwise, it will transition to "},{"type":"codeVoice","code":"STPSetupIntentStatusRequiresAction"},{"type":"text","text":", and suggest additional actions via "},{"type":"codeVoice","code":"nextAction"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Instead of passing this to "},{"type":"codeVoice","code":"STPAPIClient.confirmSetupIntent(...)"},{"type":"text","text":" directly, we recommend using "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" to handle any additional steps for you."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/title","value":"STPPaymentHandler"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/fragments","value":[{"kind":"identifier","text":"STPPaymentHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/title","value":"STPSetupIntentConfirmParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/fragments","value":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}