{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentOptionsInternalViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPCoreTableViewController","text":"STPCoreTableViewController"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stppaymentoptionsinternalviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewControllerDelegate","doc:\/\/com.stripe.stripe-ios\/objc(pl)UITableViewDataSource","doc:\/\/com.stripe.stripe-ios\/objc(pl)UITableViewDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController","interfaceLanguage":"occ"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/addCardViewController:didCreatePaymentMethod:completion:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/addCardViewControllerDidCancel:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/bankSelectionViewController:didCreatePaymentMethodParams:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/handleCancelTapped:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/handleDoneButtonTapped:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/handleEditButtonTapped:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/initWithCoder:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/initWithNibName:bundle:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/initWithTheme:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/numberOfSectionsInTableView:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/tableView:canEditRowAtIndexPath:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/tableView:cellForRowAtIndexPath:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/tableView:commitEditingStyle:forRowAtIndexPath:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/tableView:didEndEditingRowAtIndexPath:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/tableView:didSelectRowAtIndexPath:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/tableView:editingStyleForRowAtIndexPath:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/tableView:heightForFooterInSection:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/tableView:heightForHeaderInSection:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/tableView:numberOfRowsInSection:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/tableView:willBeginEditingRowAtIndexPath:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/tableView:willDisplayCell:forRowAtIndexPath:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/viewDidLayoutSubviews"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"STPPaymentOptionsInternalViewController"}],"title":"STPPaymentOptionsInternalViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Stripe@objc(cs)STPPaymentOptionsInternalViewController","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentOptionsInternalViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsInternalViewController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/stripe\/stppaymentoptionsinternalviewcontroller\/initwithcoder:"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsInternalViewController/tableView:cellForRowAtIndexPath:":{"role":"symbol","title":"tableView:cellForRowAtIndexPath:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/tableView:cellForRowAtIndexPath:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}],"url":"\/documentation\/stripe\/stppaymentoptionsinternalviewcontroller\/tableview:cellforrowatindexpath:"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsInternalViewController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/stripe\/stppaymentoptionsinternalviewcontroller\/initwithnibname:bundle:"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsInternalViewController/initWithTheme:":{"role":"symbol","title":"initWithTheme:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTheme:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/initWithTheme:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithTheme:"}],"url":"\/documentation\/stripe\/stppaymentoptionsinternalviewcontroller\/initwiththeme:"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsInternalViewController":{"role":"symbol","title":"STPPaymentOptionsInternalViewController","fragments":[{"kind":"identifier","text":"STPPaymentOptionsInternalViewController"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController","kind":"symbol","type":"topic","url":"\/documentation\/stripe\/stppaymentoptionsinternalviewcontroller"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsInternalViewController/tableView:heightForHeaderInSection:":{"role":"symbol","title":"tableView:heightForHeaderInSection:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:heightForHeaderInSection:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/tableView:heightForHeaderInSection:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:heightForHeaderInSection:"}],"url":"\/documentation\/stripe\/stppaymentoptionsinternalviewcontroller\/tableview:heightforheaderinsection:"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsInternalViewController/viewDidLayoutSubviews":{"role":"symbol","title":"viewDidLayoutSubviews","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLayoutSubviews"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/viewDidLayoutSubviews","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLayoutSubviews"}],"url":"\/documentation\/stripe\/stppaymentoptionsinternalviewcontroller\/viewdidlayoutsubviews"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsInternalViewController/handleDoneButtonTapped:":{"role":"symbol","title":"handleDoneButtonTapped:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleDoneButtonTapped:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/handleDoneButtonTapped:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"handleDoneButtonTapped:"}],"url":"\/documentation\/stripe\/stppaymentoptionsinternalviewcontroller\/handledonebuttontapped:"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsInternalViewController/tableView:editingStyleForRowAtIndexPath:":{"role":"symbol","title":"tableView:editingStyleForRowAtIndexPath:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:editingStyleForRowAtIndexPath:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/tableView:editingStyleForRowAtIndexPath:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:editingStyleForRowAtIndexPath:"}],"url":"\/documentation\/stripe\/stppaymentoptionsinternalviewcontroller\/tableview:editingstyleforrowatindexpath:"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsInternalViewController/handleEditButtonTapped:":{"role":"symbol","title":"handleEditButtonTapped:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleEditButtonTapped:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/handleEditButtonTapped:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"handleEditButtonTapped:"}],"url":"\/documentation\/stripe\/stppaymentoptionsinternalviewcontroller\/handleeditbuttontapped:"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsInternalViewController/tableView:didEndEditingRowAtIndexPath:":{"role":"symbol","title":"tableView:didEndEditingRowAtIndexPath:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:didEndEditingRowAtIndexPath:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/tableView:didEndEditingRowAtIndexPath:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:didEndEditingRowAtIndexPath:"}],"url":"\/documentation\/stripe\/stppaymentoptionsinternalviewcontroller\/tableview:didendeditingrowatindexpath:"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsInternalViewController/tableView:numberOfRowsInSection:":{"role":"symbol","title":"tableView:numberOfRowsInSection:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/tableView:numberOfRowsInSection:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}],"url":"\/documentation\/stripe\/stppaymentoptionsinternalviewcontroller\/tableview:numberofrowsinsection:"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsInternalViewController/tableView:commitEditingStyle:forRowAtIndexPath:":{"role":"symbol","title":"tableView:commitEditingStyle:forRowAtIndexPath:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:commitEditingStyle:forRowAtIndexPath:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/tableView:commitEditingStyle:forRowAtIndexPath:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:commitEditingStyle:forRowAtIndexPath:"}],"url":"\/documentation\/stripe\/stppaymentoptionsinternalviewcontroller\/tableview:commiteditingstyle:forrowatindexpath:"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsInternalViewController/tableView:didSelectRowAtIndexPath:":{"role":"symbol","title":"tableView:didSelectRowAtIndexPath:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:didSelectRowAtIndexPath:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/tableView:didSelectRowAtIndexPath:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:didSelectRowAtIndexPath:"}],"url":"\/documentation\/stripe\/stppaymentoptionsinternalviewcontroller\/tableview:didselectrowatindexpath:"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewControllerDelegate":{"role":"symbol","title":"STPAddCardViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddCardViewControllerDelegate"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPAddCardViewControllerDelegate"},{"type":"text","text":" is notified when an "},{"type":"codeVoice","code":"STPAddCardViewController"},{"type":"text","text":" "},{"type":"text","text":"successfully creates a card token or is cancelled. It has internal error-handling"},{"type":"text","text":" "},{"type":"text","text":"logic, so there’s no error case to deal with."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPAddCardViewControllerDelegate"}],"url":"\/documentation\/stripe\/stpaddcardviewcontrollerdelegate"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsInternalViewController/tableView:canEditRowAtIndexPath:":{"role":"symbol","title":"tableView:canEditRowAtIndexPath:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:canEditRowAtIndexPath:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/tableView:canEditRowAtIndexPath:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:canEditRowAtIndexPath:"}],"url":"\/documentation\/stripe\/stppaymentoptionsinternalviewcontroller\/tableview:caneditrowatindexpath:"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsInternalViewController/handleCancelTapped:":{"role":"symbol","title":"handleCancelTapped:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleCancelTapped:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/handleCancelTapped:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"handleCancelTapped:"}],"url":"\/documentation\/stripe\/stppaymentoptionsinternalviewcontroller\/handlecanceltapped:"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsInternalViewController/addCardViewControllerDidCancel:":{"role":"symbol","title":"addCardViewControllerDidCancel:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addCardViewControllerDidCancel:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/addCardViewControllerDidCancel:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addCardViewControllerDidCancel:"}],"url":"\/documentation\/stripe\/stppaymentoptionsinternalviewcontroller\/addcardviewcontrollerdidcancel:"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsInternalViewController/tableView:willBeginEditingRowAtIndexPath:":{"role":"symbol","title":"tableView:willBeginEditingRowAtIndexPath:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:willBeginEditingRowAtIndexPath:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/tableView:willBeginEditingRowAtIndexPath:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:willBeginEditingRowAtIndexPath:"}],"url":"\/documentation\/stripe\/stppaymentoptionsinternalviewcontroller\/tableview:willbegineditingrowatindexpath:"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsInternalViewController/tableView:heightForFooterInSection:":{"role":"symbol","title":"tableView:heightForFooterInSection:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:heightForFooterInSection:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/tableView:heightForFooterInSection:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:heightForFooterInSection:"}],"url":"\/documentation\/stripe\/stppaymentoptionsinternalviewcontroller\/tableview:heightforfooterinsection:"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreTableViewController":{"role":"symbol","title":"STPCoreTableViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCoreTableViewController"}],"abstract":[{"type":"text","text":"This is the base class for all Stripe scroll view controllers. It is intended"},{"type":"text","text":" "},{"type":"text","text":"for use only by Stripe classes, you should not subclass it yourself in your app."},{"type":"text","text":" "},{"type":"text","text":"It inherits from STPCoreScrollViewController and changes the type of the"},{"type":"text","text":" "},{"type":"text","text":"created scroll view to UITableView, as well as other shared table view logic."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPCoreTableViewController"}],"url":"\/documentation\/stripe\/stpcoretableviewcontroller"},"doc://com.stripe.stripe-ios/objc(pl)UITableViewDelegate":{"type":"unresolvable","title":"UITableViewDelegate","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UITableViewDelegate"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsInternalViewController/tableView:willDisplayCell:forRowAtIndexPath:":{"role":"symbol","title":"tableView:willDisplayCell:forRowAtIndexPath:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:willDisplayCell:forRowAtIndexPath:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/tableView:willDisplayCell:forRowAtIndexPath:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:willDisplayCell:forRowAtIndexPath:"}],"url":"\/documentation\/stripe\/stppaymentoptionsinternalviewcontroller\/tableview:willdisplaycell:forrowatindexpath:"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionViewControllerDelegate":{"role":"symbol","title":"STPBankSelectionViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankSelectionViewControllerDelegate"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPBankSelectionViewControllerDelegate"},{"type":"text","text":" is notified when a user selects a bank."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBankSelectionViewControllerDelegate"}],"url":"\/documentation\/stripe\/stpbankselectionviewcontrollerdelegate"},"doc://com.stripe.stripe-ios/objc(pl)UITableViewDataSource":{"type":"unresolvable","title":"UITableViewDataSource","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UITableViewDataSource"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsInternalViewController/bankSelectionViewController:didCreatePaymentMethodParams:":{"role":"symbol","title":"bankSelectionViewController:didCreatePaymentMethodParams:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bankSelectionViewController:didCreatePaymentMethodParams:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/bankSelectionViewController:didCreatePaymentMethodParams:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bankSelectionViewController:didCreatePaymentMethodParams:"}],"url":"\/documentation\/stripe\/stppaymentoptionsinternalviewcontroller\/bankselectionviewcontroller:didcreatepaymentmethodparams:"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsInternalViewController/addCardViewController:didCreatePaymentMethod:completion:":{"role":"symbol","title":"addCardViewController:didCreatePaymentMethod:completion:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addCardViewController:didCreatePaymentMethod:completion:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/addCardViewController:didCreatePaymentMethod:completion:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addCardViewController:didCreatePaymentMethod:completion:"}],"url":"\/documentation\/stripe\/stppaymentoptionsinternalviewcontroller\/addcardviewcontroller:didcreatepaymentmethod:completion:"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsInternalViewController/numberOfSectionsInTableView:":{"role":"symbol","title":"numberOfSectionsInTableView:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"numberOfSectionsInTableView:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsInternalViewController\/numberOfSectionsInTableView:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"numberOfSectionsInTableView:"}],"url":"\/documentation\/stripe\/stppaymentoptionsinternalviewcontroller\/numberofsectionsintableview:"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewControllerDelegate\/title","value":"STPAddCardViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"STPAddCardViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreTableViewController\/title","value":"STPCoreTableViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreTableViewController\/fragments","value":[{"kind":"identifier","text":"STPCoreTableViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewControllerDelegate\/title","value":"STPBankSelectionViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"STPBankSelectionViewControllerDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}