{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"stringFromAccountHolderType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType","preciseIdentifier":"c:@M@StripePayments@E@STPBankAccountHolderType","text":"STPBankAccountHolderType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"accountHolderType"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpbankaccountparams\/stringfromaccountholdertype:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams\/stringFromAccountHolderType:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stringFromAccountHolderType:"}],"title":"stringFromAccountHolderType:","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPBankAccountParams(cm)stringFromAccountHolderType:","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"stringFromAccountHolderType:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountParams":{"role":"symbol","title":"STPBankAccountParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankAccountParams"}],"abstract":[{"type":"text","text":"Representation of a user’s bank account details. You can assemble these with"},{"type":"text","text":" "},{"type":"text","text":"information that your user enters and then create Stripe tokens with them using"},{"type":"text","text":" "},{"type":"text","text":"an STPAPIClient."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBankAccountParams"}],"url":"\/documentation\/stripepayments\/stpbankaccountparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountParams/stringFromAccountHolderType:":{"role":"symbol","title":"stringFromAccountHolderType:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stringFromAccountHolderType:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams\/stringFromAccountHolderType:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stringFromAccountHolderType:"}],"url":"\/documentation\/stripepayments\/stpbankaccountparams\/stringfromaccountholdertype:"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountHolderType":{"role":"symbol","title":"STPBankAccountHolderType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankAccountHolderType"}],"abstract":[{"type":"text","text":"The type of entity that holds a bank account."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBankAccountHolderType"}],"url":"\/documentation\/stripepayments\/stpbankaccountholdertype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/title","value":"STPBankAccountParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/fragments","value":[{"kind":"identifier","text":"STPBankAccountParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType\/title","value":"STPBankAccountHolderType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType\/fragments","value":[{"kind":"identifier","text":"STPBankAccountHolderType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}