{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFormTextFieldDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"UITextFieldDelegate"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpformtextfielddelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UITextFieldDelegate"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldDelegate","interfaceLanguage":"occ"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldDelegate\/formTextField:modifyIncomingTextChange:","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldDelegate\/formTextFieldDidBackspaceOnEmpty:","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldDelegate\/formTextFieldTextDidChange:","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldDelegate\/textField:shouldChangeCharactersInRange:replacementString:"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"STPFormTextFieldDelegate"}],"title":"STPFormTextFieldDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@StripePaymentsUI@objc(pl)STPFormTextFieldDelegate","modules":[{"name":"StripePaymentsUI"}],"navigatorTitle":[{"kind":"identifier","text":"STPFormTextFieldDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"]]},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"role":"symbol","title":"STPPaymentCardTextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentCardTextField"}],"abstract":[{"type":"text","text":"STPPaymentCardTextField is a text field with similar properties to UITextField,"},{"type":"text","text":" "},{"type":"text","text":"but specialized for credit\/debit card information. It manages"},{"type":"text","text":" "},{"type":"text","text":"multiple UITextFields under the hood to collect this information. It’s"},{"type":"text","text":" "},{"type":"text","text":"designed to fit on a single line, and from a design perspective can be used"},{"type":"text","text":" "},{"type":"text","text":"anywhere a UITextField would be appropriate."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldDelegate":{"role":"symbol","title":"STPFormTextFieldDelegate","fragments":[{"kind":"identifier","text":"STPFormTextFieldDelegate"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldDelegate","kind":"symbol","type":"topic","url":"\/documentation\/stripepaymentsui\/stpformtextfielddelegate"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"role":"collection","title":"StripePaymentsUI","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","kind":"symbol","type":"topic","url":"\/documentation\/stripepaymentsui"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField":{"role":"symbol","title":"STPMultiFormTextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPMultiFormTextField"}],"abstract":[{"type":"text","text":"STPMultiFormTextField is a lightweight UIView that wraps a collection of STPFormTextFields and can automatically move to the next form field when one is completed."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPMultiFormTextField"}],"url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldDelegate/formTextField:modifyIncomingTextChange:":{"role":"symbol","title":"formTextField:modifyIncomingTextChange:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"formTextField:modifyIncomingTextChange:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldDelegate\/formTextField:modifyIncomingTextChange:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"formTextField:modifyIncomingTextChange:"}],"url":"\/documentation\/stripepaymentsui\/stpformtextfielddelegate\/formtextfield:modifyincomingtextchange:"},"doc://com.stripe.stripe-payments-ui/objc(pl)UITextFieldDelegate":{"type":"unresolvable","title":"UITextFieldDelegate","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UITextFieldDelegate"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldDelegate/formTextFieldDidBackspaceOnEmpty:":{"role":"symbol","title":"formTextFieldDidBackspaceOnEmpty:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"formTextFieldDidBackspaceOnEmpty:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldDelegate\/formTextFieldDidBackspaceOnEmpty:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"formTextFieldDidBackspaceOnEmpty:"}],"url":"\/documentation\/stripepaymentsui\/stpformtextfielddelegate\/formtextfielddidbackspaceonempty:"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldDelegate/textField:shouldChangeCharactersInRange:replacementString:":{"role":"symbol","title":"textField:shouldChangeCharactersInRange:replacementString:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textField:shouldChangeCharactersInRange:replacementString:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldDelegate\/textField:shouldChangeCharactersInRange:replacementString:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textField:shouldChangeCharactersInRange:replacementString:"}],"url":"\/documentation\/stripepaymentsui\/stpformtextfielddelegate\/textfield:shouldchangecharactersinrange:replacementstring:"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldDelegate/formTextFieldTextDidChange:":{"role":"symbol","title":"formTextFieldTextDidChange:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"formTextFieldTextDidChange:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldDelegate\/formTextFieldTextDidChange:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"formTextFieldTextDidChange:"}],"url":"\/documentation\/stripepaymentsui\/stpformtextfielddelegate\/formtextfieldtextdidchange:"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title","value":"STPPaymentCardTextField"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments","value":[{"kind":"identifier","text":"STPPaymentCardTextField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/title","value":"STPMultiFormTextField"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/fragments","value":[{"kind":"identifier","text":"STPMultiFormTextField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}