{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCoder:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"coder"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepaymentsheet\/addressviewcontroller\/initwithcoder:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/initWithCoder:","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"title":"initWithCoder:","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@StripePaymentSheet@objc(cs)STPAddressViewController(im)initWithCoder:","modules":[{"name":"StripePaymentSheet"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController"]]},"references":{"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/initwithcoder:"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController":{"role":"symbol","title":"AddressViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressViewController"}],"abstract":[{"type":"text","text":"A view controller that collects a name and an address, with full localization and autocomplete."}],"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddressViewController"}],"url":"\/documentation\/stripepaymentsheet\/addressviewcontroller"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet":{"role":"collection","title":"StripePaymentSheet","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet","kind":"symbol","type":"topic","url":"\/documentation\/stripepaymentsheet"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/title","value":"STPAddressViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/fragments","value":[{"kind":"identifier","text":"STPAddressViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}