{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"confirmPayment:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentParams","text":"STPPaymentIntentParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"paymentParams"},{"kind":"text","text":" "},{"kind":"identifier","text":"withAuthenticationContext:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<STPAuthenticationContext>","preciseIdentifier":"c:Qo@M@StripePayments@objc(pl)STPAuthenticationContext"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"authenticationContext"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(enum STPPaymentHandlerActionStatus, STPPaymentIntent *, NSError *)","preciseIdentifier":"c:BFv(#$@M@StripePayments@E@STPPaymentHandlerActionStatus#*$@M@StripePayments@objc(cs)STPPaymentIntent#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"\\param authenticationContext The authentication context used to authenticate the payment."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"\\param completion The completion block. If the status returned is "},{"type":"text","text":"STPPaymentHandlerActionStatusSucceeded"},{"type":"text","text":", the PaymentIntent status is not necessarily STPPaymentIntentStatusSucceeded (e.g. some bank payment methods take days before the PaymentIntent succeeds)."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymenthandler\/confirmpayment:withauthenticationcontext:completion:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmPayment:withAuthenticationContext:completion:","interfaceLanguage":"occ"},"abstract":[{"type":"text","text":"Confirms the PaymentIntent with the provided parameters and handles any "},{"type":"text","text":"nextAction"},{"type":"text","text":" required"},{"type":"text","text":" "},{"type":"text","text":"to authenticate the PaymentIntent."},{"type":"text","text":" "},{"type":"text","text":"Call this method if you are using automatic confirmation.  - seealso:https:\/\/stripe.com\/docs\/payments\/accept-a-payment?platform=ios&ui=custom"},{"type":"text","text":" "},{"type":"text","text":"\\param paymentParams The params used to confirm the PaymentIntent. Note that this method overrides the value of "},{"type":"text","text":"paymentParams.useStripeSDK"},{"type":"text","text":" to "},{"type":"text","text":"@YES"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"confirmPayment:withAuthenticationContext:completion:"}],"title":"confirmPayment:withAuthenticationContext:completion:","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPPaymentHandler(im)confirmPayment:withAuthenticationContext:completion:","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"confirmPayment:withAuthenticationContext:completion:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/confirmPayment:withAuthenticationContext:completion:":{"role":"symbol","title":"confirmPayment:withAuthenticationContext:completion:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"confirmPayment:withAuthenticationContext:completion:"}],"abstract":[{"type":"text","text":"Confirms the PaymentIntent with the provided parameters and handles any "},{"type":"text","text":"nextAction"},{"type":"text","text":" required"},{"type":"text","text":" "},{"type":"text","text":"to authenticate the PaymentIntent."},{"type":"text","text":" "},{"type":"text","text":"Call this method if you are using automatic confirmation.  - seealso:https:\/\/stripe.com\/docs\/payments\/accept-a-payment?platform=ios&ui=custom"},{"type":"text","text":" "},{"type":"text","text":"\\param paymentParams The params used to confirm the PaymentIntent. Note that this method overrides the value of "},{"type":"text","text":"paymentParams.useStripeSDK"},{"type":"text","text":" to "},{"type":"text","text":"@YES"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmPayment:withAuthenticationContext:completion:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"confirmPayment:withAuthenticationContext:completion:"}],"url":"\/documentation\/stripepayments\/stppaymenthandler\/confirmpayment:withauthenticationcontext:completion:"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams":{"role":"symbol","title":"STPPaymentIntentParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentParams"}],"abstract":[{"type":"text","text":"An object representing parameters used to confirm a PaymentIntent object."},{"type":"text","text":" "},{"type":"text","text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it."},{"type":"text","text":" "},{"type":"text","text":"That PaymentMethod or Source can either be:"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentParams"}],"url":"\/documentation\/stripepayments\/stppaymentintentparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler":{"role":"symbol","title":"STPPaymentHandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandler"}],"abstract":[{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" is a utility class that confirms PaymentIntents\/SetupIntents and handles any authentication required, such as 3DS1\/3DS2 for Strong Customer Authentication."},{"type":"text","text":" "},{"type":"text","text":"It can present authentication UI on top of your app or redirect users out of your app (to e.g. their banking app)."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandler"}],"url":"\/documentation\/stripepayments\/stppaymenthandler"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/title","value":"STPPaymentIntentParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/title","value":"STPPaymentHandler"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/fragments","value":[{"kind":"identifier","text":"STPPaymentHandler"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}