{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose","preciseIdentifier":"c:@M@StripePayments@E@STPFilePurpose","text":"STPFilePurpose"},{"kind":"text","text":") "},{"kind":"identifier","text":"purposeFromString:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"string"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpfile\/purposefromstring:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/purposeFromString:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"purposeFromString:"}],"title":"purposeFromString:","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPFile(cm)purposeFromString:","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"purposeFromString:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFile":{"role":"symbol","title":"STPFile","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFile"}],"abstract":[{"type":"text","text":"Representation of a file upload object in the Stripe API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPFile"}],"url":"\/documentation\/stripepayments\/stpfile"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFilePurpose":{"role":"symbol","title":"STPFilePurpose","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFilePurpose"}],"abstract":[{"type":"text","text":"The purpose of the uploaded file."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPFilePurpose"}],"url":"\/documentation\/stripepayments\/stpfilepurpose"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFile/purposeFromString:":{"role":"symbol","title":"purposeFromString:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"purposeFromString:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/purposeFromString:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"purposeFromString:"}],"url":"\/documentation\/stripepayments\/stpfile\/purposefromstring:"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile\/title","value":"STPFile"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile\/fragments","value":[{"kind":"identifier","text":"STPFile"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose\/title","value":"STPFilePurpose"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose\/fragments","value":[{"kind":"identifier","text":"STPFilePurpose"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}