{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"formTextFieldDidEndEditing:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextField","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPFormTextField","text":"STPFormTextField"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"formTextField"},{"kind":"text","text":" "},{"kind":"identifier","text":"inMultiForm:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPMultiFormTextField","text":"STPMultiFormTextField"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"multiFormField"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpaubecsdebitformview\/formtextfielddidendediting:inmultiform:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/formTextFieldDidEndEditing:inMultiForm:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"formTextFieldDidEndEditing:inMultiForm:"}],"title":"formTextFieldDidEndEditing:inMultiForm:","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@StripePaymentsUI@objc(cs)STPAUBECSDebitFormView(im)formTextFieldDidEndEditing:inMultiForm:","modules":[{"name":"StripePaymentsUI"}],"navigatorTitle":[{"kind":"identifier","text":"formTextFieldDidEndEditing:inMultiForm:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView"]]},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormView":{"role":"symbol","title":"STPAUBECSDebitFormView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAUBECSDebitFormView"}],"abstract":[{"type":"text","text":"STPAUBECSDebitFormView is a subclass of UIControl that contains all of the necessary fields and legal text for collecting AU BECS Debit payments."},{"type":"text","text":" "},{"type":"text","text":"For additional customization options - seealso: STPFormTextFieldContainer"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPAUBECSDebitFormView"}],"url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformview"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField":{"role":"symbol","title":"STPMultiFormTextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPMultiFormTextField"}],"abstract":[{"type":"text","text":"STPMultiFormTextField is a lightweight UIView that wraps a collection of STPFormTextFields and can automatically move to the next form field when one is completed."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPMultiFormTextField"}],"url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormView/formTextFieldDidEndEditing:inMultiForm:":{"role":"symbol","title":"formTextFieldDidEndEditing:inMultiForm:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"formTextFieldDidEndEditing:inMultiForm:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/formTextFieldDidEndEditing:inMultiForm:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"formTextFieldDidEndEditing:inMultiForm:"}],"url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformview\/formtextfielddidendediting:inmultiform:"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextField":{"role":"symbol","title":"STPFormTextField","fragments":[{"kind":"identifier","text":"STPFormTextField"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextField","kind":"symbol","type":"topic","url":"\/documentation\/stripepaymentsui\/stpformtextfield"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"role":"collection","title":"StripePaymentsUI","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","kind":"symbol","type":"topic","url":"\/documentation\/stripepaymentsui"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/title","value":"STPAUBECSDebitFormView"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/fragments","value":[{"kind":"identifier","text":"STPAUBECSDebitFormView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/title","value":"STPMultiFormTextField"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/fragments","value":[{"kind":"identifier","text":"STPMultiFormTextField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}