{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus","preciseIdentifier":"c:@M@StripePayments@E@STPSourceRedirectStatus","text":"STPSourceRedirectStatus"},{"kind":"text","text":") "},{"kind":"identifier","text":"statusFromString:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"string"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceredirect\/statusfromstring:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect\/statusFromString:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"statusFromString:"}],"title":"statusFromString:","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPSourceRedirect(cm)statusFromString:","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"statusFromString:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirectStatus":{"role":"symbol","title":"STPSourceRedirectStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceRedirectStatus"}],"abstract":[{"type":"text","text":"Redirect status types for a Source."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSourceRedirectStatus"}],"url":"\/documentation\/stripepayments\/stpsourceredirectstatus"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirect":{"role":"symbol","title":"STPSourceRedirect","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceRedirect"}],"abstract":[{"type":"text","text":"Information related to a source’s redirect flow."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSourceRedirect"}],"url":"\/documentation\/stripepayments\/stpsourceredirect"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirect/statusFromString:":{"role":"symbol","title":"statusFromString:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"statusFromString:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect\/statusFromString:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"statusFromString:"}],"url":"\/documentation\/stripepayments\/stpsourceredirect\/statusfromstring:"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus\/title","value":"STPSourceRedirectStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus\/fragments","value":[{"kind":"identifier","text":"STPSourceRedirectStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirect\/title","value":"STPSourceRedirect"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirect\/fragments","value":[{"kind":"identifier","text":"STPSourceRedirect"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}