{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodCardCheckResult","text":"STPPaymentMethodCardCheckResult"},{"kind":"text","text":") "},{"kind":"identifier","text":"checkResultFromString:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"string"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardchecks\/checkresultfromstring:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardChecks\/checkResultFromString:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"checkResultFromString:"}],"title":"checkResultFromString:","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardChecks(cm)checkResultFromString:","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"checkResultFromString:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardChecks"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardChecks/checkResultFromString:":{"role":"symbol","title":"checkResultFromString:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"checkResultFromString:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardChecks\/checkResultFromString:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"checkResultFromString:"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardchecks\/checkresultfromstring:"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardCheckResult":{"role":"symbol","title":"STPPaymentMethodCardCheckResult","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodCardCheckResult"}],"abstract":[{"type":"text","text":"The result of a check on a Card address or CVC."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardCheckResult"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardcheckresult"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardChecks":{"role":"symbol","title":"STPPaymentMethodCardChecks","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodCardChecks"}],"abstract":[{"type":"text","text":"Checks on Card address and CVC."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardChecks","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardChecks"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardchecks"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult\/title","value":"STPPaymentMethodCardCheckResult"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodCardCheckResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardChecks\/title","value":"STPPaymentMethodCardChecks"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardChecks\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodCardChecks"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}