{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"stringFromFlow:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow","preciseIdentifier":"c:@M@StripePayments@E@STPSourceFlow","text":"STPSourceFlow"},{"kind":"text","text":")"},{"kind":"internalParam","text":"flow"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpsource\/stringfromflow:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/stringFromFlow:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stringFromFlow:"}],"title":"stringFromFlow:","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPSource(cm)stringFromFlow:","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"stringFromFlow:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/stringFromFlow:":{"role":"symbol","title":"stringFromFlow:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stringFromFlow:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/stringFromFlow:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stringFromFlow:"}],"url":"\/documentation\/stripepayments\/stpsource\/stringfromflow:"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource":{"role":"symbol","title":"STPSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSource"}],"abstract":[{"type":"text","text":"Representation of a customer’s payment instrument created with the Stripe API. - seealso: https:\/\/stripe.com\/docs\/api#sources"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSource"}],"url":"\/documentation\/stripepayments\/stpsource"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceFlow":{"role":"symbol","title":"STPSourceFlow","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceFlow"}],"abstract":[{"type":"text","text":"Authentication flows for a Source"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSourceFlow"}],"url":"\/documentation\/stripepayments\/stpsourceflow"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/title","value":"STPSource"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/fragments","value":[{"kind":"identifier","text":"STPSource"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow\/title","value":"STPSourceFlow"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow\/fragments","value":[{"kind":"identifier","text":"STPSourceFlow"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}