{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType","preciseIdentifier":"c:@M@StripePayments@E@STPMandateCustomerAcceptanceType","text":"STPMandateCustomerAcceptanceType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"type"},{"kind":"text","text":" "},{"kind":"identifier","text":"onlineParams:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateOnlineParams","text":"STPMandateOnlineParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"onlineParams"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpmandatecustomeracceptanceparams\/initwithtype:onlineparams:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceParams\/initWithType:onlineParams:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithType:onlineParams:"}],"title":"initWithType:onlineParams:","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPMandateCustomerAcceptanceParams(im)initWithType:onlineParams:","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"initWithType:onlineParams:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceParams"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateCustomerAcceptanceType":{"role":"symbol","title":"STPMandateCustomerAcceptanceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPMandateCustomerAcceptanceType"}],"abstract":[{"type":"text","text":"The type of customer acceptance information included with the Mandate."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPMandateCustomerAcceptanceType"}],"url":"\/documentation\/stripepayments\/stpmandatecustomeracceptancetype"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateOnlineParams":{"role":"symbol","title":"STPMandateOnlineParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPMandateOnlineParams"}],"abstract":[{"type":"text","text":"Contains details about a Mandate accepted online. - seealso: https:\/\/stripe.com\/docs\/api\/payment_intents\/confirm#confirm_payment_intent-mandate_data-customer_acceptance-online"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPMandateOnlineParams"}],"url":"\/documentation\/stripepayments\/stpmandateonlineparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateCustomerAcceptanceParams/initWithType:onlineParams:":{"role":"symbol","title":"initWithType:onlineParams:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithType:onlineParams:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceParams\/initWithType:onlineParams:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithType:onlineParams:"}],"url":"\/documentation\/stripepayments\/stpmandatecustomeracceptanceparams\/initwithtype:onlineparams:"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateCustomerAcceptanceParams":{"role":"symbol","title":"STPMandateCustomerAcceptanceParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPMandateCustomerAcceptanceParams"}],"abstract":[{"type":"text","text":"An object that contains details about the customer acceptance of the Mandate. - seealso: https:\/\/stripe.com\/docs\/api\/payment_intents\/confirm#confirm_payment_intent-mandate_data-customer_acceptance"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPMandateCustomerAcceptanceParams"}],"url":"\/documentation\/stripepayments\/stpmandatecustomeracceptanceparams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceType\/title","value":"STPMandateCustomerAcceptanceType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceType\/fragments","value":[{"kind":"identifier","text":"STPMandateCustomerAcceptanceType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams\/title","value":"STPMandateOnlineParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams\/fragments","value":[{"kind":"identifier","text":"STPMandateOnlineParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceParams\/title","value":"STPMandateCustomerAcceptanceParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceParams\/fragments","value":[{"kind":"identifier","text":"STPMandateCustomerAcceptanceParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}