{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","text":"STPPaymentMethodParams"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"paramsWithWeChatPay:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodWeChatPayParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodWeChatPayParams","text":"STPPaymentMethodWeChatPayParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"weChatPay"},{"kind":"text","text":" "},{"kind":"identifier","text":"billingDetails:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"billingDetails"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadata:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,NSString *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"metadata"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"\\param billingDetails An object containing the user’s billing details."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"\\param metadata Additional information to attach to the PaymentMethod."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/paramswithwechatpay:billingdetails:metadata:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/paramsWithWeChatPay:billingDetails:metadata:","interfaceLanguage":"occ"},"abstract":[{"type":"text","text":"Creates params for a WeChat Pay PaymentMethod."},{"type":"text","text":" "},{"type":"text","text":"\\param weChatPay An object containing additional WeChat Pay details."}],"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"paramsWithWeChatPay:billingDetails:metadata:"}],"title":"paramsWithWeChatPay:billingDetails:metadata:","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@StripePayments@objc(cs)STPPaymentMethodParams(cm)paramsWithWeChatPay:billingDetails:metadata:","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"paramsWithWeChatPay:billingDetails:metadata:"}]},"hierarchy":{"paths":[[]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillingDetails":{"role":"symbol","title":"STPPaymentMethodBillingDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}],"abstract":[{"type":"text","text":"Billing information associated with a "},{"type":"codeVoice","code":"STPPaymentMethod"},{"type":"text","text":" that may be used or required by particular types of payment methods."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}],"url":"\/documentation\/stripepayments\/stppaymentmethodbillingdetails"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodWeChatPayParams":{"role":"symbol","title":"STPPaymentMethodWeChatPayParams","fragments":[{"kind":"identifier","text":"STPPaymentMethodWeChatPayParams"}],"abstract":[{"type":"text","text":"An object representing parameters used to create a WeChat Pay Payment Method"},{"type":"text","text":" "},{"type":"text","text":"WeChat Pay is currently unavailable in the iOS SDK."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodWeChatPayParams","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodwechatpayparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/paramsWithWeChatPay:billingDetails:metadata:":{"role":"symbol","title":"paramsWithWeChatPay:billingDetails:metadata:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"paramsWithWeChatPay:billingDetails:metadata:"}],"abstract":[{"type":"text","text":"Creates params for a WeChat Pay PaymentMethod."},{"type":"text","text":" "},{"type":"text","text":"\\param weChatPay An object containing additional WeChat Pay details."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/paramsWithWeChatPay:billingDetails:metadata:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paramsWithWeChatPay:billingDetails:metadata:"}],"url":"\/documentation\/stripepayments\/stppaymentmethodparams\/paramswithwechatpay:billingdetails:metadata:"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"role":"symbol","title":"STPPaymentMethodParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodParams"}],"abstract":[{"type":"text","text":"An object representing parameters used to create a PaymentMethod object."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"url":"\/documentation\/stripepayments\/stppaymentmethodparams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/title","value":"STPPaymentMethodBillingDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","value":"STPPaymentMethodParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}