{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"stringFromStatus:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus","preciseIdentifier":"c:@M@StripePayments@E@STPSourceVerificationStatus","text":"STPSourceVerificationStatus"},{"kind":"text","text":")"},{"kind":"internalParam","text":"status"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceverification\/stringfromstatus:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerification\/stringFromStatus:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stringFromStatus:"}],"title":"stringFromStatus:","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPSourceVerification(cm)stringFromStatus:","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"stringFromStatus:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerification"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceVerificationStatus":{"role":"symbol","title":"STPSourceVerificationStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceVerificationStatus"}],"abstract":[{"type":"text","text":"Verification status types for a Source."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSourceVerificationStatus"}],"url":"\/documentation\/stripepayments\/stpsourceverificationstatus"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceVerification":{"role":"symbol","title":"STPSourceVerification","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceVerification"}],"abstract":[{"type":"text","text":"Information related to a source’s verification flow."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerification","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSourceVerification"}],"url":"\/documentation\/stripepayments\/stpsourceverification"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceVerification/stringFromStatus:":{"role":"symbol","title":"stringFromStatus:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stringFromStatus:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerification\/stringFromStatus:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stringFromStatus:"}],"url":"\/documentation\/stripepayments\/stpsourceverification\/stringfromstatus:"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus\/title","value":"STPSourceVerificationStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus\/fragments","value":[{"kind":"identifier","text":"STPSourceVerificationStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerification\/title","value":"STPSourceVerification"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerification\/fragments","value":[{"kind":"identifier","text":"STPSourceVerification"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}